package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/fjglira/GoE2E-DocSyncer/internal/config"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a new docsyncer.yaml configuration file",
	Long:  `Creates a new docsyncer.yaml with sensible defaults in the current directory.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		outputPath := cfgFile

		// Check if file already exists
		if _, err := os.Stat(outputPath); err == nil {
			return fmt.Errorf("config file %q already exists; use --config to specify a different path", outputPath)
		}

		cfg := config.DefaultConfig()

		data, err := yaml.Marshal(cfg)
		if err != nil {
			return fmt.Errorf("failed to marshal default config: %w", err)
		}

		header := "# docsyncer.yaml — GoE2E-DocSyncer configuration\n" +
			"# Generated by `docsyncer init`\n" +
			"# See PLAN.md for full schema documentation.\n\n"

		if err := os.WriteFile(outputPath, []byte(header+string(data)), 0644); err != nil {
			return fmt.Errorf("failed to write config file: %w", err)
		}

		fmt.Printf("Created %s with default configuration.\n", outputPath)
		fmt.Println("Edit the file to match your project's documentation structure.")
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}
